In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/technoskill-1/test_techno.csv
/kaggle/input/technoskill-1/train_techno.csv
/kaggle/input/technoskill-1/test_sol.csv


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [3]:
data_train = pd.read_csv('../input/technoskill-1/train_techno.csv')
data_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
X = data_train.drop('price_range', axis = 1)
y = data_train['price_range']

In [5]:
X.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [6]:
y.head()

0    1
1    2
2    2
3    2
4    1
Name: price_range, dtype: int64

In [7]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  1182 non-null   int64  
 1   blue           1182 non-null   int64  
 2   clock_speed    1182 non-null   float64
 3   dual_sim       1182 non-null   int64  
 4   fc             1182 non-null   int64  
 5   four_g         1182 non-null   int64  
 6   int_memory     1182 non-null   int64  
 7   m_dep          1182 non-null   float64
 8   mobile_wt      1182 non-null   int64  
 9   n_cores        1182 non-null   int64  
 10  pc             1182 non-null   int64  
 11  px_height      1182 non-null   int64  
 12  px_width       1182 non-null   int64  
 13  ram            1182 non-null   int64  
 14  sc_h           1182 non-null   int64  
 15  sc_w           1182 non-null   int64  
 16  talk_time      1182 non-null   int64  
 17  three_g        1182 non-null   int64  
 18  touch_sc

In [8]:
data_train.describe()

battery_power         blue  clock_speed     dual_sim           fc  \
count    1182.000000  1182.000000  1182.000000  1182.000000  1182.000000   
mean     1248.247885     0.483080     1.525212     0.512690     4.363790   
std       440.202286     0.499925     0.814781     0.500051     4.411859   
min       501.000000     0.000000     0.500000     0.000000     0.000000   
25%       853.250000     0.000000     0.700000     0.000000     1.000000   
50%      1260.000000     0.000000     1.500000     1.000000     3.000000   
75%      1631.000000     1.000000     2.200000     1.000000     7.000000   
max      1997.000000     1.000000     3.000000     1.000000    18.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  1182.000000  1182.000000  1182.000000  1182.000000  1182.000000  ...   
mean      0.501692    33.044839     0.501692   141.590525     4.487310  ...   
std       0.500209    18.166523     0.287911    35.375999     2.285193  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    17.000000     0.200000   110.000000     3.000000  ...   
50%       1.000000    33.000000     0.500000   142.000000     4.000000  ...   
75%       1.000000    49.000000     0.800000   172.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  1182.000000  1182.000000  1182.000000  1182.000000  1182.000000   
mean    647.015228  1249.471235  2162.908629    12.317259     5.748731   
std     441.411624   428.669203  1096.283957     4.217823     4.360780   
min       1.000000   500.000000   258.000000     5.000000     0.000000   
25%     287.000000   875.500000  1211.500000     9.000000     2.000000   
50%     561.000000  1247.000000  2227.000000    12.000000     5.000000   
75%     952.750000  1613.000000  3109.500000    16.000000     9.000000   
max    1949.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  1182.000000  1182.000000   1182.000000  1182.000000  1182.000000  
mean     11.038917     0.749577      0.507614     0.519459     1.537225  
std       5.361307     0.433440      0.500154     0.499833     1.125436  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       7.000000     0.250000      0.000000     0.000000     1.000000  
50%      11.000000     1.000000      1.000000     1.000000     2.000000  
75%      16.000000     1.000000      1.000000     1.000000     3.000000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 24)

# Logistic Regression

In [10]:
clf_regression = LogisticRegression().fit(X_train,y_train)
clf_regression.score(X_test,y_test)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.6418918918918919

# Gaussian

In [11]:
gnb = GaussianNB()
clf_gnb = gnb.fit(X_train, y_train)
clf_gnb.score(X_test, y_test)

0.8006756756756757

# K-nearest Neighbors

In [12]:
neigh = KNeighborsClassifier(n_neighbors=9)
clf_knn = neigh.fit(X_train, y_train)
clf_knn.score(X_test, y_test)

0.9155405405405406

# Decision Tree

In [13]:
clf_dt = tree.DecisionTreeClassifier()
clf_dectree = clf_dt.fit(X_train, y_train)
clf_dectree.score(X_test, y_test)

0.8277027027027027

# Random Forest

In [14]:
clf_rf = RandomForestClassifier(max_depth=22)
clf_rf.fit(X_train, y_train)
clf_rf.score(X_test, y_test)

0.8412162162162162

# SVC

In [15]:
clf_svc = svm.SVC(kernel = 'poly', gamma = 'auto', verbose = True, degree = 2)
clf_svc.fit(X_train, y_train)
y_predict = clf_svc.predict(X_test)
clf_svc.score(X_test, y_test)

[LibSVM]

0.972972972972973

In [16]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        77
           1       0.96      0.97      0.97        71
           2       0.96      0.96      0.96        75
           3       0.97      0.99      0.98        73

    accuracy                           0.97       296
   macro avg       0.97      0.97      0.97       296
weighted avg       0.97      0.97      0.97       296



# Confusion Matrix

In [17]:
konfyus = confusion_matrix(y_test, y_predict)
print(konfyus)

[[75  2  0  0]
 [ 0 69  2  0]
 [ 0  1 72  2]
 [ 0  0  1 72]]


In [18]:
data_test = pd.read_csv('../input/technoskill-1/test_techno.csv')
data_test.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            709     0          1.9         0  11       1          13    0.1   
1           1744     0          2.8         0   0       1          62    0.7   
2           1314     1          2.2         0   0       1          40    0.8   
3           1136     0          0.5         0   0       1           9    0.9   
4           1039     1          2.7         0  11       0          56    0.3   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0         81        8  ...        570      1422   467    17    11          5   
1        158        1  ...        621      1558   345    10     6         14   
2        116        7  ...        328      1858  3033     9     8         17   
3        150        6  ...       1307      1767  2110     9     5         16   
4        125        8  ...        497       618  3105    14     8          5   

   three_g  touch_screen  wifi  id  
0        1             1     1   1  
1        1             0     0   2  
2        1             1     1   3  
3        1             0     1   4  
4        0             1     1   5  

[5 rows x 21 columns]

In [19]:
data_test.drop('id', axis = 1, inplace = True)
data_test.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            709     0          1.9         0  11       1          13    0.1   
1           1744     0          2.8         0   0       1          62    0.7   
2           1314     1          2.2         0   0       1          40    0.8   
3           1136     0          0.5         0   0       1           9    0.9   
4           1039     1          2.7         0  11       0          56    0.3   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0         81        8  15        570      1422   467    17    11          5   
1        158        1   0        621      1558   345    10     6         14   
2        116        7   1        328      1858  3033     9     8         17   
3        150        6   2       1307      1767  2110     9     5         16   
4        125        8  13        497       618  3105    14     8          5   

   three_g  touch_screen  wifi  
0        1             1     1  
1        1             0     0  
2        1             1     1  
3        1             0     1  
4        0             1     1

In [20]:
data_lol = data_test
data_lol.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            709     0          1.9         0  11       1          13    0.1   
1           1744     0          2.8         0   0       1          62    0.7   
2           1314     1          2.2         0   0       1          40    0.8   
3           1136     0          0.5         0   0       1           9    0.9   
4           1039     1          2.7         0  11       0          56    0.3   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0         81        8  15        570      1422   467    17    11          5   
1        158        1   0        621      1558   345    10     6         14   
2        116        7   1        328      1858  3033     9     8         17   
3        150        6   2       1307      1767  2110     9     5         16   
4        125        8  13        497       618  3105    14     8          5   

   three_g  touch_screen  wifi  
0        1             1     1  
1        1             0     0  
2        1             1     1  
3        1             0     1  
4        0             1     1

In [21]:
pricerange_predict = clf_svc.predict(data_test)
pricerange_predict

array([0, 0, 3, 2, 2, 0, 3, 2, 0, 3, 2, 0, 1, 2, 2, 1, 0, 2, 0, 2, 1, 2,
       1, 1, 3, 0, 1, 1, 2, 0, 3, 1, 2, 2, 1, 3, 2, 0, 2, 2, 1, 3, 0, 0,
       3, 2, 1, 2, 0, 0, 2, 3, 2, 0, 0, 0, 2, 3, 0, 2, 2, 1, 1, 1, 2, 1,
       0, 2, 1, 3, 3, 0, 0, 2, 3, 1, 3, 1, 0, 3, 3, 0, 1, 3, 1, 1, 3, 3,
       1, 3, 0, 1, 1, 3, 2, 0, 0, 3, 1, 3, 1, 2, 2, 3, 0, 3, 1, 1, 0, 3,
       1, 2, 0, 2, 2, 3, 2, 0, 3, 1, 0, 3, 3, 1, 1, 0, 3, 1, 3, 1, 1, 2,
       0, 1, 3, 3, 3, 3, 1, 3, 0, 1, 1, 0, 1, 3, 1, 1, 2, 1, 1, 1, 1, 2,
       2, 1, 3, 3, 2, 1, 1, 2, 1, 2, 3, 2, 0, 3, 3, 2, 3, 3, 2, 1, 1, 2,
       1, 1, 0, 0, 0, 0, 2, 1, 1, 2, 0, 2, 0, 2, 2, 0, 3, 1, 0, 3, 0, 1,
       3, 3, 0, 0, 1, 1, 3, 2, 3, 0, 2, 1, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0,
       2, 2, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2, 2, 0, 1, 3, 0, 0, 2, 2, 3,
       1, 1, 1, 1, 2, 1, 1, 3, 0, 3, 0, 1, 0, 1, 0, 0, 3, 2, 1, 0, 2, 1,
       0, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 2, 1, 3, 3, 0, 3, 2, 0, 1, 2, 3,
       3, 0, 1, 1, 1, 1, 3, 1, 1, 0, 2, 3, 1, 3, 1,

In [22]:
data_test['price_range'] = pricerange_predict
data_test.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            709     0          1.9         0  11       1          13    0.1   
1           1744     0          2.8         0   0       1          62    0.7   
2           1314     1          2.2         0   0       1          40    0.8   
3           1136     0          0.5         0   0       1           9    0.9   
4           1039     1          2.7         0  11       0          56    0.3   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0         81        8  ...        570      1422   467    17    11          5   
1        158        1  ...        621      1558   345    10     6         14   
2        116        7  ...        328      1858  3033     9     8         17   
3        150        6  ...       1307      1767  2110     9     5         16   
4        125        8  ...        497       618  3105    14     8          5   

   three_g  touch_screen  wifi  price_range  
0        1             1     1            0  
1        1             0     0            0  
2        1             1     1            3  
3        1             0     1            2  
4        0             1     1            2  

[5 rows x 21 columns]

In [23]:
data_submission = pd.read_csv('../input/technoskill-1/test_sol.csv')
data_submission.head()

Id  price_range
0   1            0
1   2            0
2   3            0
3   4            0
4   5            0

In [24]:
data_submission['price_range'] = pricerange_predict
data_submission.head()

Id  price_range
0   1            0
1   2            0
2   3            3
3   4            2
4   5            2

In [25]:
data_submission.to_csv("pricerangeprediction.csv", index = False)
